### ISSUE TITLE
Do these primitives cover all possible arc tests?

### ISSUE THREAD

**Issue by nullbio** [michaelhodel/arc-dsl#2]
Do we know if composing these primitives, and these primitives alone, would cover every possible arc puzzle? Or could it be the case that there are puzzles that cannot be solved by a composition of these primitives, and would require new primitives being developed? I noticed that you do solve for all 400, but I'm curious about future puzzles. 

Perhaps this isn't even an answerable question, but I'm sure you've put some thought into this: Whether there are primitives that are low level enough to be composable in enough ways (within a reasonable number of base primitives, i.e. not requiring the composition of hundreds of base primitives) to build any possible primitive to solve any possible arc puzzle imaginable. I suppose you could look at this is a question in the realm of turing completeness for the arc puzzle domain.

**Comment by michaelhodel** [comment]
Good question. 

Given that ARC (as a puzzle domain - not as the fixed set of 1000 tasks) by definition kind of allows any task that can be viewed as a mix of only the core knowledge priors, which are arguably almost all-encompassing, it seems to me that for a DSL to be "ARC-complete" it also needs to also be (quasi) Turing-complete in the first place as a necessary condition. While I haven't tried to proved it, I'm pretty sure that this DSL is turing-complete. Then again, I think that getting sufficient expressivity of a DSL (say defining "sufficient" as "there exists a pure-DSL program for >= 85% of the hidden test tasks") is not the hard part or the part to worry about. You nailed it by writing "not requiring the composition of hundreds of base primitives": There is a trade-off between the expressivity of the DSL and the conciseness of the solution programs (i.e. the larger they are, the harder they are to construct/be found/be verified etc.).

Two (fun) facts that may be helpful here:

1. After I fixed the DSL by only informing it by the training set, I used the DSL to write solution programs for all the evaluation tasks too, among other reasons to "test" the DSL. That was doable, and while some of the solver programs for evaluation tasks required usage of very many dozens of DSL primitive calls, I managed to write a pure-DSL program for all the 400 evaluation tasks, only the median solver size was a bit bigger (though arguably the evaluation set is also harder than the training set, so hard to separate out the effect of e.g. "overfitting the DSL to the training set"). So that's partly where I get my "DSL expressivity per se is not an issue" intuition.

2. I once rewrote >80% of my DSL within itself, i.e. compressed the DSL down to only 28 base primitives (I stopped there not because it couldn't have been compressed further, but because it was getting cumbersome because of circular dependency issues etc. and didn't really plan to use it anyway), so a DSL of this size is definitely not needed to have the same expressivity! I myself am very unsure about the ideal number of primitives for an "optimal DSL" (where obviously what constitutes an optimal DSL arguably largely depends on the specific use case in the first place, i.e. how it is intended to be used).

E.g. I did things like these:

def invert(n): return multiply(n, NEG_ONE)
def even(n): return equality(double(halve(n)), n)
def double(n): return multiply(n, TWO)
def increment(x): return add(x, ONE)
def positive(x): return greater(x, ZERO)
...

Hopefully that is useful!


PS: I am happy to take "adversarial attacks" to the DSL as a fun challenge, i.e. anyone coming up with a new ARC-task and challenging me to write a pure-DSL solution program for it.

**Comment by nullbio** [comment]
@michaelhodel Thanks for the thoughtful response.

Since you've offered, how about this for a challenge? I have no idea if this is something that is already covered by the existing Arc challenges, it was something I was curious about (whether wrapping was something that was currently used in puzzles), so if it is, perhaps you've already encountered this. 

Anyway, the idea is puzzles that utilizing toroidal grid wrapping. There are a lot of unique twists you could do on this concept too, for example, wrapped elements could mirror in the opposite of the expected position, they could flip bits/colors, overlapping elements could cancel each-other out, and so forth. But to keep it simple, here's a basic demo of what I mean (ignore the messy code, got ChatGPT to help me hack it up - it's pretty gross, but can help you generate your own combinations if it's something you wanted to experiment with, and it provides the arrays):

https://codepen.io/Patrick-OBrien/pen/mdYqayG

And some screenshots to illustrate: 

![example1](https://github.com/michaelhodel/arc-dsl/assets/721274/9d8a8ccd-ee02-432e-b9d4-712215ef9b36)
![example2](https://github.com/michaelhodel/arc-dsl/assets/721274/bf88885f-822f-4433-9fca-23adb58ba521)

**Comment by michaelhodel** [comment]
@nullbio I don't get the task you posted but you can definitely solve wrapping tasks:

```
from random import randint, sample, choice
from dsl import *

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, Normalize


def plot_task(task):
    """ plots a task """
    cmap = ListedColormap([
        '#000', '#0074D9', '#FF4136', '#2ECC40', '#FFDC00',
        '#AAAAAA', '#F012BE', '#FF851B', '#7FDBFF', '#870C25'
    ])
    norm = Normalize(vmin=0, vmax=9)
    args = {'cmap': cmap, 'norm': norm}
    height = 2
    width = len(task)
    figure_size = (width * 2, height * 2)
    figure, axes = plt.subplots(height, width, figsize=figure_size)
    if width == 1:
        axes[0].imshow(task[0]['input'], **args)
        axes[1].imshow(task[0]['output'], **args)
        axes[0].axis('off')
        axes[1].axis('off')
    else:
        for column, example in enumerate(task):
            axes[0, column].imshow(example['input'], **args)
            axes[1, column].imshow(example['output'], **args)
            axes[0, column].axis('off')
            axes[1, column].axis('off')
    figure.set_facecolor('#1E1E1E')
    plt.subplots_adjust(wspace=0.1, hspace=0.1)
    plt.show()


def generate_wrap_example(di, dj):
    h = randint(5, 10)
    w = randint(5, 10)
    bgc = randint(0, 9)
    c = canvas(bgc, (h, w))
    remc = remove(bgc, interval(0, 10, 1))
    nc = randint(1, (h*w)//2-1)
    locs = sample(totuple(asindices(c)), nc)
    obj = {(choice(remc), ij) for ij in locs}
    gi = paint(c, obj)
    rotf = lambda cij: (cij[0], ((cij[1][0]+di)%h, (cij[1][1]+dj)%w))
    go = paint(c, apply(rotf, obj))
    return {"input": gi, "output": go}


def solve_wrap_example(I, di, dj):
    h = height(I)
    w = width(I)
    ofsf = rbind(add, astuple(di, dj))
    imodh = fork(subtract, identity, compose(rbind(multiply, h), rbind(divide, h)))
    jmodw = fork(subtract, identity, compose(rbind(multiply, w), rbind(divide, w)))
    rotf = fork(astuple, compose(imodh, first), compose(jmodw, last))
    f = fork(astuple, first, chain(rotf, ofsf, last))
    obj = merge(fgpartition(I))
    O = paint(cover(I, obj), apply(f, obj))
    return O


ntasks = 4
nexpertask = 6
maxshift = 3
for _ in range(ntasks):
    di = randint(-maxshift, maxshift)
    dj = randint(-maxshift, maxshift)
    print(di, dj)
    t = [generate_wrap_example(di, dj) for k in range(nexpertask)]
    assert all(solve_wrap_example(ex['input'], di, dj) == ex['output'] for ex in t)
    plot_task(t)
```

![wraptask](https://github.com/michaelhodel/arc-dsl/assets/45543779/41cb237d-2e95-441e-8631-1ad3f420b026)
